# Generated by Django 5.1.2 on 2024-10-24 06:35

from django.db import migrations, models
import uuid

def populate_product_id(apps, schema_editor):
    NewInventory = apps.get_model('tickets', 'NewInventory')
    for item in NewInventory.objects.filter(product_id=None):
        item.product_id = uuid.uuid4()  # Generate a unique UUID for each item
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),  # Adjust this to your actual migration
    ]

    operations = [
        # Add the product_id field without enforcing the uniqueness constraint yet
        migrations.AddField(
            model_name='newinventory',
            name='product_id',
            field=models.UUIDField(null=True),  # Temporarily allow null values
        ),
        
        # Populate existing records with unique values
        migrations.RunPython(populate_product_id),
        
        # Now enforce the unique constraint on the product_id field
        migrations.AlterField(
            model_name='newinventory',
            name='product_id',
            field=models.UUIDField(unique=True),  # Now enforce uniqueness
        ),
    ]
