# Generated by Django 5.1.2 on 2024-10-24 06:35

from django.db import migrations
import uuid

def generate_unique_product_id(apps, schema_editor):
    NewInventory = apps.get_model('tickets', 'NewInventory')
    for item in NewInventory.objects.filter(product_id=None):
        item.product_id = uuid.uuid4()  # Generate unique UUID for each product
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_newinventory_product_id'),  # The previous migration
    ]

    operations = [
        migrations.RunPython(generate_unique_product_id),  # Run custom function to populate product_id
    ]
