# Generated by Django 5.1.2 on 2024-10-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_customuser_email'),
        ('tickets', '0004_auto_20241024_0235'),
    ]

    operations = [
    ]
