# Generated by Django 5.1.2 on 2024-10-31 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_newinventory_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.newinventory'),
        ),
    ]
